Oseed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='Home'),
    path('', views.login_view, name='login'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('inventario/', include('inventario.urls'), name='inventario'),
    path('clientes/', include('clientes.urls'), name='clientes'),
    path('solicitudes/', include('solicitudes.urls'), name='solicitudes'),
    path('usuarios/', include('usuarios.urls'), name='usuarios'),
    path('rutas_gps/', include('rutas_gps.urls'), name='rutas_gps'),
    path('auditoria/', include('auditoria.urls'), name='auditoria'),
    path('select2/', include('django_select2.urls')),
    path('cerrar_sesion/', views.cerrar_sesion, name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.inventario, name='inventario'),
    path('categoria/<id>/', views.view_categorias, name='view_categoria'),
    path("stock/", views.main_stock, name='inventario_general'),
    path("agregarProductos/", views.addProducts, name='addProducto'),
    path('update/<id>/', views.updateProduct, name='uptProduct'),
    path('delete/<id>/', views.eliminarProducto, name='dltProduct'),

    #Reportes
    path('reporteStock/', views.reporte_stock.as_view(), name="pdf_stock"),
    path('export/', views.export_stock_to_excel, name='excel_stock'),
    path('reporte/pdf/<int:id>/', views.generar_reporte_pdf.as_view(), name='reporte_pdf'),
    path('reporte/excel/<int:id>/', views.generar_reporte_excel, name='reporte_excel'),
    path('agregarCategoria/', views.agregarCategoria, name='add_categoria'),
    path('updateCategoria/<id>/', views.updateCategoria, name='uptCategoria'),
    path('deleteCategoria/<id>/', views.eliminarCategoria, name='dltCategoria'),
    
    path('producto/<int:producto_id>/transacciones/', views.producto_transacciones, name='producto_transacciones'),
    path('reporte_transacciones/<int:producto_id>/', views.ReporteTransacciones.as_view(), name='reporte_transacciones_pdf'),
    path("agregarUnidad/", views.agregarUnidad, name='addUnidad'),
    path('actualizarUnidad/<int:id>/', views.updateUnidad, name='updateUnidad'),
    path('eliminarUnidad/<int:id>/', views.eliminarUnidad, name='deleteUnidad'),

    path('bodegas/', views.bodegas, name='bodegas'),
    path('bodegas/verBodega/<int:id>/', views.verBodegas, name='verBodega'),
    path('bodegas/agregar/', views.agregar_bodega, name='agregar_bodega'),
    path('bodegas/actualizar/<int:id>/', views.actualizar_bodega, name='actualizar_bodega'),
    path('bodegas/eliminar/<int:id>/', views.eliminar_bodega, name='eliminar_bodega'),

    # Rutas para Subcategorías
    path('subcategorias/', views.listar_subcategorias, name='listar_subcategorias'),
    path('subcategorias/agregar/', views.agregar_subcategoria, name='agregar_subcategoria'),
    path('subcategorias/actualizar/<int:id>/', views.actualizar_subcategoria, name='actualizar_subcategoria'),
    path('subcategorias/eliminar/<int:id>/', views.eliminar_subcategoria, name='eliminar_subcategoria'),

    # Rutas para Precios por Unidad
    path('precios/unidad/', views.agregar_precio_por_unidad, name='addPrecioPorUnidad'),
    path('precios/unidad/actualizar/<int:id>/', views.actualizar_precio_por_unidad, name='actualizar_precio_por_unidad'),
    path('precios/unidad/eliminar/<int:id>/', views.eliminar_precio_por_unidad, name='eliminar_precio_por_unidad'),

    # Rutas para Historial de Precios
    path('historial/precio/', views.agregar_historial_precio, name='addHistorialPrecio'),
    path('historial/precio/actualizar/<int:id>/', views.actualizar_historial_precio, name='actualizar_historial_precio'),
    path('historial/precio/eliminar/<int:id>/', views.eliminar_historial_precio, name='eliminar_historial_precio'),

    # Rutas para Variaciones de Producto
    path('variaciones/producto/', views.agregar_variacion_producto, name='addVariacionProducto'),
    path('variaciones/producto/actualizar/<int:id>/', views.actualizar_variacion_producto, name='actualizar_variacion_producto'),
    path('variaciones/producto/eliminar/<int:id>/', views.eliminar_variacion_producto, name='eliminar_variacion_producto'),

    # Rutas para Stock en Bodega
    path('bodega/crear/', views.agregar_stock_bodega, name='addStockBodega'),
    path('bodega/actualizar/<int:id>/', views.actualizar_stock_bodega, name='actualizar_stock_bodega'),

]

inventario/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from PIL import Image
from auditlog.registry import auditlog
from django.contrib.auth.models import User
import re
from usuarios.models import CustomUser

def validate_non_negative(value):
    if value < 0:
        raise ValidationError('Este campo no puede ser un número negativo.')

def validate_image_size(value):
    max_size = 5 * 1024 * 1024
    if value.size > max_size:
        raise ValidationError('La imagen no puede superar los 5 MB.')

def validate_image_dimensions(value):
    max_dimensions = (270, 270)
    image = Image.open(value)
    width, height = image.size
    if width > max_dimensions[0] or height > max_dimensions[1]:
        raise ValidationError('Las dimensiones de la imagen no pueden ser mayores a 270x270 píxeles.')


class Categorias(models.Model):
    nombre = models.CharField(max_length=20)
    portada = models.ImageField(
        upload_to='categorias/',  # <-- Cambiado aquí
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
            validate_image_size,
            validate_image_dimensions,
        ]
    )

    def clean(self):
        if not re.match("^[A-Za-z]*$", self.nombre):
            raise ValidationError("El nombre solo puede contener letras.")

    def __str__(self):
        return self.nombre

class SubCategoria(models.Model):
    nombre = models.CharField(max_length=50)
    categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE, related_name='subcategorias')

    def __str__(self):
        return f'{self.categoria.nombre} - {self.nombre}'

class Unidades(models.Model):
    unidad = models.CharField(max_length=20)

    def clean(self):
        if not re.match("^[A-Za-z]*$", self.unidad):
            raise ValidationError("La unidad solo puede contener letras.")

    def __str__(self):
        return self.unidad

class UnidadesVenta(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre

def validate_codigo(value):
    regex = r"^BOD-\d{4}$"
    if not re.match(regex, value):
        raise ValidationError('El código debe tener el formato BOD-0000.')

class Bodega(models.Model):
    codigo = models.CharField(max_length=20, unique=True, validators=[validate_codigo])
    nombre = models.CharField(max_length=100)
    ubicacion = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.nombre} ({self.codigo})'

class Stock(models.Model):
    producto = models.CharField(max_length=20)
    cantidad = models.IntegerField(validators=[validate_non_negative])
    unidad = models.ForeignKey(Unidades, on_delete=models.CASCADE)
    unidad_venta = models.ForeignKey(UnidadesVenta, on_delete=models.CASCADE, null=True, blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_non_negative])
    categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    existencia_min = models.IntegerField(validators=[validate_non_negative])
    imagen = models.ImageField(
        upload_to='productos/',  # <-- Cambiado aquí
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']),
            validate_image_size,
        ], blank=True, null=True
    )

    def __str__(self):
        return f'{self.producto} ({self.unidad_venta})'

    def vender_producto(self, cantidad):
        if cantidad > self.cantidad:
            raise ValidationError('No hay suficiente stock para realizar esta transacción.')
        else:
            self.cantidad -= cantidad
            self.save()

    def __str__(self):
        return self.producto

class PrecioPorUnidad(models.Model):
    producto = models.ForeignKey(Stock, on_delete=models.CASCADE)
    unidad_venta = models.ForeignKey(UnidadesVenta, on_delete=models.CASCADE)
    precio = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_non_negative])

    def __str__(self):
        return f'{self.producto} - {self.unidad_venta} - {self.precio}'

class TransaccionInventario(models.Model):
    TIPOS_TRANSACCION = [
        ('ENTRADA', 'Entrada'),
        ('SALIDA', 'Salida'),
        ('AJUSTE', 'Ajuste'),
    ]

    producto = models.ForeignKey(Stock, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=7, choices=TIPOS_TRANSACCION)
    cantidad = models.IntegerField(validators=[validate_non_negative])
    fecha = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    motivo = models.CharField(max_length=100, blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.tipo == 'SALIDA' and self.cantidad > self.producto.cantidad:
            raise ValidationError('No hay suficiente stock para realizar esta transacción.')
        elif self.tipo == 'SALIDA':
            self.producto.cantidad -= self.cantidad
        elif self.tipo == 'ENTRADA':
            self.producto.cantidad += self.cantidad
        self.producto.save()
        super(TransaccionInventario, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.producto} - {self.tipo} - {self.cantidad}'


class HistorialPrecio(models.Model):
    producto = models.ForeignKey(Stock, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    precio_anterior = models.DecimalField(max_digits=10, decimal_places=2)
    precio_nuevo = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.producto} - {self.precio_anterior} -> {self.precio_nuevo}'


class VariacionProducto(models.Model):
    producto = models.ForeignKey(Stock, on_delete=models.CASCADE)
    nombre_variacion = models.CharField(max_length=50)
    valor = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.producto} - {self.nombre_variacion}: {self.valor}'


class StockBodega(models.Model):
    producto = models.ForeignKey(Stock, on_delete=models.CASCADE)
    bodega = models.ForeignKey(Bodega, on_delete=models.CASCADE)
    cantidad = models.IntegerField(validators=[validate_non_negative])

    def __str__(self):
        return f'{self.producto} en {self.bodega}'


auditlog.register(Categorias)
auditlog.register(Unidades)
auditlog.register(Stock)
auditlog.register(TransaccionInventario)
auditlog.register(PrecioPorUnidad)
auditlog.register(StockBodega)
auditlog.register(HistorialPrecio)

inventario/templates/categoria.html
{% extends 'dashmenu/main.html' %}

{% block content %}
<div class="main-panel">

  <div class="content-wrapper">
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          {% if messages %}
          {% for m in messages %}
            <div class="alert alert-success" role="alert">
                {{m}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>         
          {% endfor %}
        {% endif %}
          <div class="d-flex justify-content-end align-items-start">
            <div class="input-group" style="width: auto;">
              <form method="GET" action="{% url 'inventario_general' %}" class="form-inline my-2 my-lg-0">
                <div class="form-group">
                    <input type="text" name="q" class="form-control mr-sm-2" placeholder="Buscar producto...">
                </div>
            </form>
            </div>
          </div>
          <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">{{categoria.nombre}}</h4>
                <div class="table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Unidad</th>
                        <th>Status</th>
                        <th>Precio</th>
                        <th>Categoria</th>
                        {% if perms.inventario.change_categorias %}
                        <th>Acciones</th>
                        {% endif %}
                      </tr>
                    </thead>
                    <tbody>
                      {% for p in productos %}
                      <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{p.producto}}</td>
                        <td>{{p.cantidad}}</td>
                        <td>{{p.unidad}}</td>
                        {% if p.cantidad >= 50 %}
                        <td><label class="badge badge-success">Disponible</label></td>
                        {% elif p.cantidad >= 1 %}
                        <td><label class="badge badge-warning">Reabastecer</label></td>
                        {% else %}
                        <td><label class="badge badge-danger">Agotado</label></td>
                        {% endif %}
                        <td>{{p.precio}}$</td>
                        <td>{{p.categoria}}</td>
                        <td>
                          <div>
                            {% if perms.inventario.change_categorias %}
                            <a href="{% url 'uptProduct' p.id %}"><button class="btn btn-warning"><i class="fa fa-undo" aria-hidden="true"></i></button></a>
                            {% endif %}
                            {% if perms.inventario.delete_categorias %}
                            <a href="{% url 'dltProduct' p.id %}"><button class="btn btn-danger btnEliminacion"><i class="fa fa-trash" aria-hidden="true"></i></button></a>
                            {% endif %}
                          </div>
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <div>
                    <center>{% include 'paginator.html' %}</center>
                </div>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-center mt-2 flex-wrap">
            <a href="{% url 'reporte_excel' categoria.id %}" target="_blank"><button class="btn btn-success btn-lg m-2">Generar Excel</button></a>
            <a href="{% url 'reporte_pdf' categoria.id %}" target="_blank"><button class="btn btn-danger btn-lg m-2">Generar PDF</button></a>
        </div>
        
        
        </div>
      </div>
    </div>
{% endblock %}

inventario/templates/categorias.html
{% extends 'dashmenu/main.html' %}
{% load crispy_forms_filters %} 
{% load crispy_forms_tags %} 

{% block content %}
<div class="main-panel">
  <div class="content-wrapper">
    <div class="col-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Agregar Categoria</h4>
          <form action="" method="post" enctype="multipart/form-data" class="forms-sample">
            <div class="form-group">
              {% csrf_token %}
              {{form | crispy}}
            </div>
            <button type="submit" class="btn btn-primary mr-2">Agregar Categoria</button>
            <a href="javascript: history.go(-1)"></a><button class="btn btn-outline-light">Cancel</button>
          </form>
        </div>
      </div>
    </div>

{% endblock %}

inventario/templates/inventario.html
{% extends 'dashmenu/main.html' %}
{% load static %}

{% block content %}
<div class="main-panel">
  <div class="content-wrapper">
    {% if messages %}
    {% for m in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{m}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>         
    {% endfor %}
{% endif %}
<div class="row">
    <div class="col-md-12 grid-margin">
      <div class="row">
        <div class="col-12 col-xl-8 mb-4 mb-xl-0">
          <h3 class="font-weight-bold">Gestión de Inventario</h3>
        </div>
      </div>
    </div>
  </div>
    <div class="row">
      <div class="col-md-4 grid-margin stretch-card">
        <div class="card tale-bg">
          <div class="card-people mt-auto">
            <img src="{% static 'images/dashboard/people.svg'%}" alt="people">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb-4 stretch-card transparent d-flex justify-content-center">
            <a href="{% url 'inventario_general' %}" style="text-decoration: none; color: #ffffff; max-width: 600px;">
                <div class="card card-tale" style="background-color: cornflowerblue;">
                    <div class="card-body">
                        <p class="mb-4">Inventario General</p>
                        <p class="fs-30 mb-2">{{stock}}</p>  
                    </div>
                </div>
            </a>
        </div>
        {% if perms.inventario.add_categorias %}
        <div class="col-md-6 mb-4 stretch-card transparent d-flex justify-content-center">
            <a href="{% url 'add_categoria' %}" style="text-decoration: none; color: #ffffff; max-width: 600px;">
                <div class="card card-tale" style="background-color: darkblue;">
                    <div class="card-body">
                        <p class="mb-4">Añadir</p>
                        <p class="fs-30 mb-2">Categorias <i class="fa fa-file-text-o" aria-hidden="true"></i> </p>  
                    </div>
                </div>
            </a>
        </div>
        {% endif %}
        <div class="col-md-6 mb-4 stretch-card transparent d-flex justify-content-center">
            <a href="{% url 'pdf_stock' %}" target="_blank" style="text-decoration: none; color: #ffffff; max-width: 600px;">
                <div class="card card-tale" style="background-color: darkred;">
                    <div class="card-body">
                        <p class="mb-4">Descargar Reporte</p>
                        <p class="fs-30 mb-2">PDF <i class="fa fa-file-pdf-o" aria-hidden="true"></i> </p>  
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6 mb-4 stretch-card transparent d-flex justify-content-center">
            <a href="{% url 'excel_stock' %}" target="_blank" style="text-decoration: none; color: #ffffff; max-width: 600px;">
                <div class="card card-tale" style="background-color: darkgreen;">
                    <div class="card-body">
                        <p class="mb-4">Descargar Reporte</p>
                        <p class="fs-30 mb-2">Excel <i class="fa fa-file-excel-o" aria-hidden="true"></i> </p>  
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% if perms.inventario.view_categorias %}
      <div class="row">
        {% for c, total in cat_total %}
        <div class="col-md-3 mb-4 stretch-card transparent d-flex justify-content-center">
            <div class="card card-tale" style="background-color: cornflowerblue; width: 300px; position: relative;">
                <div class="dropdown" style="position: absolute; top: 10px; right: 10px;">
                    {% if perms.inventario.change_categorias %}
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background: none;color: #ffffff; border: none;">
                    </button>
                    {% endif %}
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      {% if perms.inventario.change_categorias %}
                        <a class="dropdown-item" href="{% url 'uptCategoria' c.id %}">Modificar</a>
                      {% endif %}
                      {% if perms.inventario.delete_categorias %}
                        <a class="dropdown-item btnEliminacion" href="{% url 'dltCategoria' c.id %}">Eliminar</a>
                      {% endif %}
                    </div>
                </div>
                <a href="{% url 'view_categoria' c.id %}" style="text-decoration: none; color: #ffffff;">
                    <div class="card-body">
                        <p class="mb-4">{{c.nombre}}</p>
                        <p class="fs-30 mb-2">{{total}}</p>  
                    </div>
                </a>
            </div>
        </div>
    {% endfor %}
    
    </div>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

inventario/templates/stock.html
{% extends 'dashmenu/main.html' %}

{% block content %}
<div class="main-panel">

  <div class="content-wrapper">
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          {% if messages %}
          {% for m in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{m}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>         
          {% endfor %}
      {% endif %}
          <div class="d-flex justify-content-end align-items-start">
            <div class="input-group" style="width: auto;">
              <form method="GET" action="{% url 'inventario_general' %}" class="form-inline my-2 my-lg-0">
                <div class="form-group">
                    <input type="text" name="q" class="form-control mr-sm-2" placeholder="Buscar producto...">
                </div>
            </form>
            </div>
          </div>
          <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Inventario General</h4>
                <div class="table-responsive">
                  <table class="table table-hover text-center">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th><a href="{% url 'addUnidad' %}" style="text-decoration: none; color: #000;">Unidad</a></th>
                            <th>Status</th>
                            <th>Precio</th>
                            <th>Categoria</th>
                            <th>Detalles</th>
                            {% if perms.inventario.change_stock %}
                            <th>Acciones</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in stock %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>
                            {% if p.cantidad == 0 %}
                              <span class="alert alert-danger" style="margin: 0.5rem;">
                                ¡Atención! El producto {{ p.producto }} se ha agotado.
                              </span>
                          {% elif p.cantidad <= p.existencia_min %}
                              <span class="alert alert-warning" style="margin: 0.5rem;">
                                ¡Atención! El producto {{ p.producto }} ha alcanzado su existencia mínima.
                              </span>
                          {% else %}
                            {{p.producto}}
                          {% endif %}
                        </td>                       
                            <td>{{p.cantidad}}</td>
                            <td>{{p.unidad}}</td>
                            {% if p.cantidad >= p.existencia_min %}
                            <td><label class="badge badge-success">Disponible</label></td>
                            {% elif p.cantidad >= 1 %}
                            <td><label class="badge badge-warning">Reabastecer</label></td>
                            {% else %}
                            <td><label class="badge badge-danger">Agotado</label></td>
                            {% endif %}
                            <td>{{p.precio}}$</td>
                            <td>{{p.categoria}}</td>
                            {% if perms.inventario.view_stock %}
                            <td>
                              <a href="{% url 'producto_transacciones' p.id %}">
                                <button class="btn btn-success"><i class="fa fa-eye" aria-hidden="true"></i></button>
                              </a>
                          </td>
                          {% endif %}
                            <td>
                                <div>
                                  {% if perms.inventario.change_stock %}
                                    <a href="{% url 'uptProduct' p.id %}"><button class="btn btn-warning"><i class="fa fa-undo" aria-hidden="true"></i></button></a>
                                    {% endif %}
                                    {% if perms.inventario.delete_stock %}
                                    <a href="{% url 'dltProduct' p.id %}"><button class="btn btn-danger btnEliminacion"><i class="fa fa-trash" aria-hidden="true"></i></button></a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                <div>
                    <center>{% include 'paginator.html' %}</center>
                </div>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-center mt-2 flex-wrap">
            <a href="{% url 'excel_stock' %}" target="_blank"><button class="btn btn-success btn-lg m-2">Generar Excel</button></a>
            <a href="{% url 'pdf_stock' %}" target="_blank"><button class="btn btn-danger btn-lg m-2">Generar PDF</button></a>
            {% if perms.inventario.add_stock %}
            <a href="{% url 'addProducto' %}"><button class="btn btn-primary btn-lg m-2">Registrar Productos</button></a>
            {% endif %}
        </div>
      </div>
    </div>
  </div>

{% endblock %}

inventario/templates/unidades.html
{% extends 'dashmenu/main.html' %}
{% load crispy_forms_filters %} 
{% load crispy_forms_tags %} 
{% block content %}
<div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      {% if perms.inventario.add_unidades %}
      <div class="col-md-6">
        <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              {% if messages %} {% for m in messages %}
              <div
                class="alert alert-success alert-dismissible fade show"
                role="alert"
              >
                {{m}}
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"
                ></button>
              </div>
              {% endfor %} {% endif %}
              <h4 class="card-title">Agregar Unidades</h4>
              <form
                action=""
                method="post"
                enctype="multipart/form-data"
                class="forms-sample"
              >
                <div class="form-group">{% csrf_token %} {{form | crispy}}</div>
                <center>
                  <button type="submit" class="btn btn-primary mr-2">
                    Agregar Unidad
                  </button>
                </center>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Unidades Agregadas</h4>
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Asociados</th>
                    {% if perms.inventario.change_unidades %}
                    <th>Acciones</th>
                    {% endif %}
                  </tr>
                </thead>
                <tbody>
                  {% for u in unidad %}
                  <tr>
                    <td>{{u.unidad}}</td>
                    <td>{{u.productos_count}}</td>
                    <td>
                      <div>
                        {% if perms.inventario.change_unidades %}
                        <a href="{% url 'updateUnidad' u.id %}"
                          ><button class="btn btn-warning">
                            <i
                              class="fa fa-undo"
                              aria-hidden="true"
                            ></i></button
                        ></a>
                        {% endif %} {% if perms.inventario.delete_unidades %}
                        <a href="{% url 'deleteUnidad' u.id %}"
                          ><button class="btn btn-danger btnEliminacion">
                            <i
                              class="fa fa-trash"
                              aria-hidden="true"
                            ></i></button
                        ></a>
                        {% endif %}
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              <div>
                <center>{% include 'paginator.html' %}</center>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

inventario/templates/updateCategoria.html
{% extends 'dashmenu/main.html' %}
{% load crispy_forms_filters %} 
{% load crispy_forms_tags %} 

{% block content %}
<div class="main-panel">
  <div class="content-wrapper">
    <div class="col-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Actualizar Categoria</h4>
          <form action="" method="post" enctype="multipart/form-data" class="forms-sample">
            <div class="form-group">
              {% csrf_token %}
              {{form | crispy}}
            </div>
            <button type="submit" class="btn btn-primary mr-2">Actualizar Categoria</button>
            <a href="{% url 'inventario' %}" class="btn btn-outline-light">Cancelar</a>
          </form>
        </div>
      </div>
  </div>

{% endblock %}