Oseed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'), name='Home'),
    path('', views.login_view, name='login'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('inventario/', include('inventario.urls'), name='inventario'),
    path('clientes/', include('clientes.urls'), name='clientes'),
    path('solicitudes/', include('solicitudes.urls'), name='solicitudes'),
    path('usuarios/', include('usuarios.urls'), name='usuarios'),
    path('rutas_gps/', include('rutas_gps.urls'), name='rutas_gps'),
    path('auditoria/', include('auditoria.urls'), name='auditoria'),
    path('select2/', include('django_select2.urls')),
    path('cerrar_sesion/', views.cerrar_sesion, name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
from usuarios.views import detalles_usuario
from inventario.views import main_stock

urlpatterns = [
    path("", views.dashboard, name='dashboard'),
    path('buscar/', views.buscar, name='buscar'),
    path('usuarios/<int:user_id>/', detalles_usuario, name='detalles_usuario'),
    path("stock/", main_stock, name='inventario_general'),
    path('clientCard/<int:id>/', views.clienteCard, name='clienteCard'),
    path('shopCard/<int:id>/', views.shopCard, name='shopCard'),
        path('dashboard_json/', views.dashboard_json, name='dashboard_json'),
    path('error404/', views.error404, name='E404')
]

clientes/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re
from auditlog.registry import auditlog

# Función para validar el RIF
def validar_rif(value):
    if not value[0].isupper():
        raise ValidationError("El RIF debe comenzar con una letra mayúscula.")

    regex = r"^[A-Z]-\d{8}-\d$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El RIF no tiene el formato correcto.")

# Modelo Tiendas
class Tiendas(models.Model):
    Cliente = models.CharField(max_length=100)
    RIF = models.CharField(max_length=12, unique=True, validators=[validar_rif])
    Direccion = models.TextField()
    Status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.Cliente

    def get_status_display(self):
        return "Activo" if self.Status else "Inactivo"

    def get_badge_class(self):
        return "success" if self.Status else "danger"

    def resumen(self):
        return f"{self.Cliente} | RIF: {self.RIF} | Dirección: {self.Direccion} | Estatus: {self.get_status_display()}"

# Validación de nombre
def validar_nombre(value):
    regex = r"^[a-zA-Z ]+$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El nombre no tiene el formato correcto.")

def validar_cedula(value):
    regex = r"^(\d{2}\.\d{3}\.\d{3}|\d{1}\.\d{3}\.\d{3})$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("La cédula no tiene el formato correcto. Debe ser 'XX.XXX.XXX' o 'X.XXX.XXX'.")

# Validación de correo electrónico
def validar_correo(value):
    regex = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El correo no tiene el formato correcto.")

# Validación de teléfono
def validar_telefono(value):
    regex = r"^\+\d{1,4}\d{9,}$"  # + seguido de 1 a 4 dígitos y luego 9 o más dígitos adicionales
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El teléfono no tiene el formato correcto. Debe empezar con '+' seguido de al menos 10 dígitos.")

# Modelo Clientes
class Clientes(models.Model):
    Nombre = models.CharField(max_length=20, validators=[validar_nombre])
    Apellido = models.CharField(max_length=20, validators=[validar_nombre])
    Cedula = models.CharField(max_length=12, unique=True, validators=[validar_cedula])
    Correo = models.EmailField(unique=True, validators=[validar_correo])
    Telefono = models.CharField(max_length=15, validators=[validar_telefono])
    Tienda = models.ForeignKey(Tiendas, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.Nombre} {self.Apellido}"

# Auditorías para la aplicación "Clientes"
auditlog.register(Clientes)
auditlog.register(Tiendas)

dashboard/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from PIL import Image
import re
from auditlog.registry import auditlog

# Validación para el peso máximo de la imagen (2 MB)
def validate_image_size(value):
    max_size = 2 * 1024 * 1024  # 2 MB en bytes
    if value.size > max_size:
        raise ValidationError(_('El tamaño de la imagen no puede exceder los 2 MB.'))

class Cargos(models.Model):
    Nombre = models.CharField(max_length=20)

    def __str__(self):
        return self.Nombre

def validar_nombre(value):
    regex = r"^[a-zA-Z ]+$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El nombre no tiene el formato correcto.")

def validar_cedula(value):
    regex = r"^\d{2}\.\d{3}\.\d{3}$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("La cédula no tiene el formato correcto.")

def validar_correo(value):
    regex = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El correo no tiene el formato correcto.")

def validar_telefono(value):
    regex = r"^\+\d{1,4}\d{9,}$"  # + seguido de 1 a 4 dígitos y luego 9 o más dígitos adicionales
    pattern = re.compile(regex)
    if not pattern.match(value):
        raise ValidationError("El teléfono no tiene el formato correcto. Debe empezar con algun prefijo '+58' seguido del número.")

class CustomUser(AbstractUser):
    nombre = models.CharField(max_length=100, validators=[validar_nombre])
    apellido = models.CharField(max_length=100, validators=[validar_nombre])
    cedula = models.CharField(max_length=20, validators=[validar_cedula])
    direccion = models.TextField()
    telefono = models.CharField(max_length=15, validators=[validar_telefono])
    cargo = models.ForeignKey(Cargos, on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField(unique=True)
    imagen_perfil = models.ImageField(upload_to='perfil/', default='perfil/default.jpg', validators=[validate_image_size])
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre + " " + self.apellido

auditlog.register(CustomUser)

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from inventario.models import *
from clientes.models import *
from usuarios.models import *
from clientes.views import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import redirect
from solicitudes.models import *
from django.http import JsonResponse
from django.core.serializers import serialize
from django.utils import timezone
# Create your views here.

@login_required
def dashboard(request):
    st = Stock.objects.all().count()
    cl = Tiendas.objects.all().count()
    total_usuarios = CustomUser.objects.count()
    
    facturas_recientes = Factura.objects.all().order_by('-fecha_creacion')[:10]
    
    # Formatear la fecha en el formato deseado con "am" o "pm"
    formatted_facturas_recientes = [{
      'fecha_creacion': timezone.localtime(factura.fecha_creacion).strftime("%m/%d/%Y %I:%M:%S %p"),
        'usuario': factura.usuario,
        'tienda': factura.tienda,
        'total': factura.total
    } for factura in facturas_recientes]

    facturas = Factura.objects.all()

    return render(request, "dashboard.html", {
        'st_counter': st,
        'chocolate': cl,
        'vanila': total_usuarios,
        'ordenes_recientes': formatted_facturas_recientes,
        'facturas': facturas,
        'page_title': 'Oseed | Dashboard'
    })

@login_required
def dashboard_json(request):
    st_count = Factura.objects.all().count()  # Número total de facturas
    tiendas_count = Factura.objects.values('tienda').distinct().count()  # Número total de tiendas con al menos una factura
    total_usuarios = Factura.objects.values('usuario').distinct().count()  # Número total de usuarios con al menos una factura
    
    # Obtener las 10 facturas más recientes
    facturas_recientes = Factura.objects.all().order_by('-fecha_creacion')[:10]
    
    # Formatear las facturas recientes en formato JSON
    formatted_facturas_recientes = [{
       'fecha_creacion': timezone.localtime(factura.fecha_creacion).strftime("%m/%d/%Y %I:%M:%S %p"),
        'usuario': factura.usuario.username,
        'tienda': factura.tienda.Cliente if factura.tienda else '',  
        'cliente': factura.cliente,
        'status': factura.status  # Aquí es donde se cambió a 'status'
    } for factura in facturas_recientes]

    # Crear un diccionario con los datos
    data = {
        'st_counter': st_count,
        'chocolate': tiendas_count,
        'vanila': total_usuarios,
        'ordenes_recientes': formatted_facturas_recientes,
    }

    # Devolver los datos en formato JSON
    return JsonResponse(data)

@login_required
def buscar(request):
    if 'q' in request.GET:
        query = request.GET['q']
        
        if not query:
            messages.error(request, 'Por favor, introduce un criterio de búsqueda.')
            return redirect('dashboard')
        
        try:
            # Intenta buscar un usuario por su nombre de usuario
            user = CustomUser.objects.get(username=query)
            return redirect('detalles_usuario', user_id=user.id)
        except CustomUser.DoesNotExist:
            pass

        try:
            # Intenta buscar un usuario por su nombre
            user = CustomUser.objects.get(nombre__icontains=query)
            return redirect('detalles_usuario', user_id=user.id)
        except CustomUser.DoesNotExist:
            pass

        try:
            # Intenta buscar un usuario por su cédula
            user = CustomUser.objects.get(cedula=query)
            return redirect('detalles_usuario', user_id=user.id)
        except CustomUser.DoesNotExist:
            pass

        try:
            # Intenta buscar un cliente por su nombre o apellido
            cliente = Clientes.objects.get(Nombre__icontains=query)
            return redirect('clientCard', id=cliente.id)
        except Clientes.DoesNotExist:
            pass

        try:
            # Intenta buscar una tienda por el nombre del cliente o por el RIF
            tienda = Tiendas.objects.filter(Cliente__icontains=query).first() or Tiendas.objects.get(RIF=query)
            return redirect('shopCard', id=tienda.id)
        except Tiendas.DoesNotExist:
            pass

        try:
            # Intenta buscar un producto por su ID
            producto_id = int(query)
            producto = Stock.objects.get(id=producto_id)
            return redirect('producto_transacciones', producto_id=producto.id)
        except (ValueError, Stock.DoesNotExist):
            pass

        try:
            # Intenta buscar un producto por su nombre
            producto = Stock.objects.filter(producto__icontains=query).first()
            if producto:
                return redirect('producto_transacciones', producto_id=producto.id)
            else: pass
        except Stock.DoesNotExist:
            messages.error(request, 'Error al buscar el producto.')

    return redirect('E404')

def error404(request): return render(request, "error-404.html")

dashboard/templates/dashboard.html
{% extends 'dashmenu/main.html' %}
{% load static %}

{% block content %}
<div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-md-12 grid-margin">
              <div class="row">
                <div class="col-12 col-xl-8 mb-4 mb-xl-0">
                  {% if messages %}
                  {% for m in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                      {{ m }}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                  {% endfor %}
                {% endif %}
                <h3 class="font-weight-bold">Bienvenido {% if user.is_authenticated %} {{user.nombre}} {{user.apellido}} {% endif %}</h3>
              </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
              <div class="card tale-bg">
                <div class="card-people mt-auto">
                  <img src="{% static 'images/dashboard/people.svg'%}" alt="people">
                </div>
              </div>
            </div>
            <div class="col-md-6 grid-margin transparent">
              <div class="row">
                {% if perms.clientes.view_clientes %}
                <div class="col-md-6 mb-4 stretch-card transparent">
                  <div class="card card-tale">
                    <a href="{% url 'cliente' %}" style="color: aliceblue; text-decoration: none;">
                    <div class="card-body">
                      <p class="mb-4">Clientes</p>
                      <p class="fs-30 mb-2">{{chocolate}}</p>
                    </div>
                    </a>
                  </div>
                </div>
                {% endif %}
                {% if perms.usuarios.view_customuser %}
                <div class="col-md-6 mb-4 stretch-card transparent">
                  <div class="card card-dark-blue">
                    <a href="{% url 'usuarios' %}" style="color: aliceblue; text-decoration: none;">
                    <div class="card-body">
                      <p class="mb-4">Usuarios</p>
                      <p class="fs-30 mb-2">{{vanila}}</p>
                    </div>
                  </a>
                  </div>
                </div>
                {% endif %}
              </div>
              <div class="row">
                {% if perms.inventario.view_stock %}
                <div class="col-md-6 mb-4 mb-lg-0 stretch-card transparent">
                  <div class="card card-light-blue">
                    <a href="{% url 'inventario' %}" style="color: aliceblue; text-decoration: none;">
                    <div class="card-body">
                      <p class="mb-4">Productos</p>
                      <p class="fs-30 mb-2">{{st_counter}}</p>
                    </div>
                    </a>
                  </div>
                </div>
                {% endif %}
                <div class="col-md-6 stretch-card transparent">
                  <div class="card card-light-danger">
                    <div class="card-body">
                      <p class="mb-4">Ganancias</p>
                      <p class="fs-30 mb-2">0$</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
              <div class="card position-relative">
                <div class="card-body">
                  <div id="detailedReports" class="carousel slide detailed-report-carousel position-static pt-2" data-ride="carousel">
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <div class="row">
                          <div class="col-md-12 col-xl-3 d-flex flex-column justify-content-start">
                            <div class="ml-xl-4 mt-3">
                            <p class="card-title">Detalles de Ventas</p>
                              <h1 class="text-primary">$34040</h1>
                              <h3 class="font-weight-500 mb-xl-4 text-primary">(Nombre de la tienda)</h3>
                              <p class="mb-2 mb-xl-0">Agregar descripcion del conductor que realizo la venta y el lugar donde la hizo</p>
                            </div>  
                            </div>
                          <div class="col-md-12 col-xl-9">
                            <div class="row">
                              <div class="col-md-6 border-right">
                                <div class="table-responsive mb-3 mb-md-0 mt-3">
                                  <table class="table table-borderless report-table">
                                    <tr>
                                      <td class="text-muted">Producto #1</td>
                                      <td class="w-100 px-0">
                                        <div class="progress progress-md mx-4">
                                          <div class="progress-bar bg-primary" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                      </td>
                                      <td><h5 class="font-weight-bold mb-0">713</h5></td>
                                    </tr>
                                    <tr>
                                      <td class="text-muted">Producto #2</td>
                                      <td class="w-100 px-0">
                                        <div class="progress progress-md mx-4">
                                          <div class="progress-bar bg-warning" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                      </td>
                                      <td><h5 class="font-weight-bold mb-0">583</h5></td>
                                    </tr>
                                    <tr>
                                      <td class="text-muted">Producto #3</td>
                                      <td class="w-100 px-0">
                                        <div class="progress progress-md mx-4">
                                          <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                      </td>
                                      <td><h5 class="font-weight-bold mb-0">924</h5></td>
                                    </tr>
                                    <tr>
                                      <td class="text-muted">Producto #4</td>
                                      <td class="w-100 px-0">
                                        <div class="progress progress-md mx-4">
                                          <div class="progress-bar bg-info" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                      </td>
                                      <td><h5 class="font-weight-bold mb-0">664</h5></td>
                                    </tr>
                                    <tr>
                                      <td class="text-muted">Producto #5</td>
                                      <td class="w-100 px-0">
                                        <div class="progress progress-md mx-4">
                                          <div class="progress-bar bg-primary" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                      </td>
                                      <td><h5 class="font-weight-bold mb-0">560</h5></td>
                                    </tr>
                                    <tr>
                                      <td class="text-muted">Producto #6</td>
                                      <td class="w-100 px-0">
                                        <div class="progress progress-md mx-4">
                                          <div class="progress-bar bg-danger" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                      </td>
                                      <td><h5 class="font-weight-bold mb-0">793</h5></td>
                                    </tr>
                                  </table>
                                </div>
                              </div>
                              <div class="col-md-6 mt-3">
                                <canvas id="north-america-chart"></canvas>
                                <div id="north-america-legend"></div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#detailedReports" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#detailedReports" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
</div>
<script>
  // Función para actualizar los datos de órdenes recientes cada 5 segundos
  function actualizarOrdenesRecientes() {
      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {
              var data = JSON.parse(this.responseText);
              
              // Actualizar el cuerpo de la tabla de órdenes recientes
              var ordenesRecientesHTML = "";
              data.ordenes_recientes.forEach(function(factura) {
                  ordenesRecientesHTML += "<tr>";
                  ordenesRecientesHTML += "<td>" + factura.fecha_creacion + "</td>";
                  ordenesRecientesHTML += "<td>" + factura.usuario + "</td>";
                  ordenesRecientesHTML += "<td>" + factura.tienda + "</td>";
                  ordenesRecientesHTML += "<td>"+  factura.cliente +"</td>";
                  ordenesRecientesHTML += "<td><span class=\"badge " + (factura.status ? 'badge-success">Entregado' : 'badge-warning">En Proceso...') + "</span></td>";
                  ordenesRecientesHTML += "</tr>";
              });
              document.getElementById("tbody").innerHTML = ordenesRecientesHTML;
          }
      };
      xhttp.open("GET", "{% url 'dashboard_json' %}", true);
      xhttp.send();
  }

  // Llamar a la función para actualizar los datos de órdenes recientes cada 5 segundos
  setInterval(actualizarOrdenesRecientes, 15000); // 5000 milisegundos = 5 segundos

  // Llamar a la función inicialmente para cargar los datos de órdenes recientes
  actualizarOrdenesRecientes();
</script>
{% endblock %}

dashboard/templates/error-404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'js/select.dataTables.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
</head>
<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
        <div class="row flex-grow">
          <div class="col-lg-7 mx-auto text-white">
            <div class="row align-items-center d-flex flex-row">
              <div class="col-lg-6 text-lg-right pr-lg-4">
                <h1 class="display-1 mb-0">404</h1>
              </div>
              <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                <h2>Lo Sentimos</h2>
                <h3 class="font-weight-light">No se encontró un usuario, cliente, tienda o producto con este criterio de búsqueda.</h3>
              </div>
            </div>
            <div class="row mt-5">
              <div class="col-12 text-center mt-xl-2">
                <a class="text-white font-weight-medium" href="{% url 'dashboard' %}">Regresar Al Dashboard</a>
              </div>
            </div>
            <div class="row mt-5">
              <div class="col-12 mt-xl-2">
                <p class="text-white font-weight-medium text-center">Copyright &copy; 2024  All rights reserved. TechnOS</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="../../vendors/js/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="../../js/off-canvas.js"></script>
  <script src="../../js/hoverable-collapse.js"></script>
  <script src="../../js/template.js"></script>
  <script src="../../js/settings.js"></script>
  <script src="../../js/todolist.js"></script>
  <!-- endinject -->
</body>

</html>